# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loopr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loopr
  pod 'SwiftLint'

  target 'looprTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'looprUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
