# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loopr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loopr
  # Flutter
  flutter_application_path = '../flutter/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'NotificationBannerSwift'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON', '~> 4.0'

  target 'looprTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'looprUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
